### ISSUE TITLE
Problem with pubspec.yaml and duct

### ISSUE THREAD

**Issue by ghost** [petrhosek/duct#10]
Here is my pubspec.yaml file:

```
name: "CSGOBlinks"
dependencies:
  polymer: "^1.0.0-rc.3"
  web_components: ^0.12.0
  reflectable: "^0.3.3"
  polymer_elements: "^1.0.0-rc.2"
  duct:
      git: git://github.com/petrhosek/duct.git ">=0.4.3"
transformers:
- web_components:
    entry_points:
      - web/index.html
- reflectable:
    entry_points:
      - web/index.dart
```

and here is the output of pub install. Is that something that can be fixed? I have no clue

```
➜  CSGOBlinks_front git:(dev) ✗ pub install
Resolving dependencies... (2.9s) 
Incompatible version constraints on logging:
- csslib 0.12.2 depends on version >=0.9.0 <0.12.0
- duct 0.0.1 depends on version >=0.4.3
- redis_client 0.1.13 depends on version >=0.9.0 <0.10.0
- reflectable 0.3.3 depends on version ^0.11.0
```
